// JS CONSTRUCTOR FUNCTIONS

// A CONSTRUCTOR FUNCTION IS USED TO DEFINE A CUSTOM 
// TYPE, FROM WHICH MULTIPLE OBJECTS CAN BE CREATED 
// WITH SIMILAR PROPERTIES

// THE "NEW" KEYWORD IS USED TO DECLARE A NEW OBJECT

// THE NAME OF A CONSTRUCTOR FUNCTION STARTS WITH 
// A CAPITAL LETTER







