// WHAT NUMBER WILL THIS FUNCTION RETURN?

(() => {
    try {
        return 2;
    } finally {
        return 3
    }
})();

// OBSERVATIONS:

// - WE KNOW A FINALLY BLOCK WILL ALWAYS RUN 
// REGARDLESS OF THE OUTCOME OF THE TRY BLOCK
// - IT CAN BE SEEN THAT BOTH THE TRY BLOCK AND 
// FINALLY BLOCK ARE RETURNING A VALUE

// ANSWER:

// IF A FINALLY BLOCK IS RETURNING A VALUE, THIS 
// VALUE BECOMES THE RETURN VALUE OF THE ENTIRE 
// TRY-CATCH-FINALLY STATEMENT, REGARDLESS OF 
// ANY RETURN STATEMENTS IN THE TRY AND CATCH
// BLOCKS, AS WELL AS ANY EXCEPTIONS THROWN
// INSIDE OF THE CATCH BLOCK




